import {
  RECONCILIATION_ADJUSTMENT_CATEGORY,
  OPENING_BALANCE_CATEGORY,
  RECONCILIATION_LEDGER_CATEGORIES,
  REASON_MIN_LENGTH,
  isReconciliationLedgerCategory,
  appCalendarTodayYmd,
  isValidReason,
  normalizeReason,
  yearMonthFromYmd,
} from './constants';
import {
  previewCashAccountReconcile,
  previewRevaluation,
  previewHoldingQuantityReconcile,
  previewSukukPrincipalRestatement,
  previewFromInput,
  computeReconcileDelta,
  isNoopDelta,
  accountHasLedgerActivity,
  resolveCashReconcileMechanism,
  portfolioIdsForAccount,
} from './preview';
import { buildIdempotencyKey, reasonHash } from './idempotency';
import {
  buildCashReconcileLedgerTransaction,
  buildBrokerCashReconcileInvestmentRow,
  pendingApprovalsBlockAccount,
  isCashReconcileEligibleAccount,
  mechanismForEntity,
  isInvestmentReconciliationCashAdjustment,
  investmentLedgerTypeLabel,
  isInvestmentLedgerTypeCapitalInflow,
  isInvestmentLedgerTypeCapitalOutflow,
  INVESTMENT_RECONCILIATION_NOTE_PREFIX,
} from './cashDelta';
import {
  insertNetWorthSnapshotRevision,
  fetchLatestNetWorthSnapshotRevisions,
  latestRevisionPerDay,
  nextSnapshotRevisionNumber,
  normalizeNetWorthSnapshotRevisionRow,
} from './snapshotRevisions';
import {
  insertReconciliationAdjustment,
  insertReconciliationAudit,
  insertReconciliationRun,
  updateReconciliationRunStatus,
  markAdjustmentReversed,
  fetchReconciliationAuditEvents,
  fetchReconciliationAdjustments,
  fetchReconciliationRuns,
  auditEventsToCsv,
} from './auditStore';
import { assertCanReverseAdjustment, reverseTargets, buildReverseCashLedgerTx, buildReverseBrokerCashRow } from './reverse';
import {
  assertTransferEditAllowed,
  describeTransferDeleteCascade,
  isTransferLeg,
  transferDeleteCascadeIds,
  transferGroupIdOf,
  transferLegsForGroup,
} from './transferSafety';
import {
  replayAffectedPortfolioSymbols,
  collectMissingMarks,
  buildReplayRunPayload,
} from './replay';
import type {
  ApplyReconciliationInput,
  ApplyReconciliationResult,
  ReconciliationAdjustment,
  ReconciliationAuditEvent,
  ReconciliationPreview,
  ReconciliationRun,
} from './types';
import {
  normalizeReconciliationAdjustmentRow,
  normalizeReconciliationAuditRow,
  normalizeReconciliationRunRow,
} from './types';

export {
  RECONCILIATION_ADJUSTMENT_CATEGORY,
  OPENING_BALANCE_CATEGORY,
  RECONCILIATION_LEDGER_CATEGORIES,
  REASON_MIN_LENGTH,
  isReconciliationLedgerCategory,
  appCalendarTodayYmd,
  isValidReason,
  normalizeReason,
  yearMonthFromYmd,
  previewCashAccountReconcile,
  previewRevaluation,
  previewHoldingQuantityReconcile,
  previewSukukPrincipalRestatement,
  previewFromInput,
  computeReconcileDelta,
  isNoopDelta,
  accountHasLedgerActivity,
  resolveCashReconcileMechanism,
  portfolioIdsForAccount,
  buildIdempotencyKey,
  reasonHash,
  buildCashReconcileLedgerTransaction,
  buildBrokerCashReconcileInvestmentRow,
  isInvestmentReconciliationCashAdjustment,
  investmentLedgerTypeLabel,
  isInvestmentLedgerTypeCapitalInflow,
  isInvestmentLedgerTypeCapitalOutflow,
  INVESTMENT_RECONCILIATION_NOTE_PREFIX,
  pendingApprovalsBlockAccount,
  isCashReconcileEligibleAccount,
  mechanismForEntity,
  insertNetWorthSnapshotRevision,
  fetchLatestNetWorthSnapshotRevisions,
  latestRevisionPerDay,
  nextSnapshotRevisionNumber,
  normalizeNetWorthSnapshotRevisionRow,
  insertReconciliationAdjustment,
  insertReconciliationAudit,
  insertReconciliationRun,
  updateReconciliationRunStatus,
  markAdjustmentReversed,
  fetchReconciliationAuditEvents,
  fetchReconciliationAdjustments,
  fetchReconciliationRuns,
  auditEventsToCsv,
  assertCanReverseAdjustment,
  reverseTargets,
  buildReverseCashLedgerTx,
  buildReverseBrokerCashRow,
  assertTransferEditAllowed,
  describeTransferDeleteCascade,
  isTransferLeg,
  transferDeleteCascadeIds,
  transferGroupIdOf,
  transferLegsForGroup,
  replayAffectedPortfolioSymbols,
  collectMissingMarks,
  buildReplayRunPayload,
  normalizeReconciliationAdjustmentRow,
  normalizeReconciliationAuditRow,
  normalizeReconciliationRunRow,
};

export type {
  ApplyReconciliationInput,
  ApplyReconciliationResult,
  ReconciliationAdjustment,
  ReconciliationAuditEvent,
  ReconciliationPreview,
  ReconciliationRun,
};

export type {
  NetWorthSnapshotRevision,
  NetWorthSnapshotRevisionInput,
  NetWorthSnapshotRevisionBuckets,
} from './snapshotRevisions';
